import type { Metadata } from "next";

import  {Playfair_Display } from "next/font/google";
import "./globals.css";
import TabNavigation from "@/components/tab-navigation"

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  weight: ["400", "700"],
  style: ["italic", "normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} antialiased`}
      >
        <TabNavigation />
        {children}
      </body>
    </html>
  );
}
